FROM python:3.10-slim

WORKDIR /app

COPY requirements-producer.txt .
RUN pip install --no-cache-dir -r requirements-producer.txt

COPY producers/ ./producers/
COPY alerts/ ./alerts/
COPY config/ ./config/

CMD ["python", "producers/producer_temperatura.py"]
